### ISSUE TITLE
cntv脚本两天前的修改造成频道节目单无法显示

### ISSUE THREAD

**Issue by lychichem** [xinggsf/gm#17]
脚本第75行的`.vo_nr,.vo_nr>div`这个选择器会造成问题，导致图中红框位置不显示：
![image](https://user-images.githubusercontent.com/9316590/94557394-145bb500-0291-11eb-8204-fa172a6fa524.png)
删除此选择器则一切正常

**Comment by lychichem** [comment]
我现在理解你的想法是处理掉视频播放器右侧的相关视频部分，我的一个处理方式是在脚本最后加一句`$(".left_but").click()`触发这个按钮的click事件，就能把右侧隐藏了，虽然效果上有点延迟

**Comment by xinggsf** [comment]
相关CSS是用于视频右侧滚动条高度调整，已修正BUG.

下载更新：
https://gitee.com/xinggsf/gm
